# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_auth_form(object):
    def setupUi(self, auth_form):
        auth_form.setObjectName("auth_form")
        auth_form.resize(472, 404)
        self.login = QtWidgets.QLineEdit(auth_form)
        self.login.setGeometry(QtCore.QRect(60, 120, 361, 31))
        self.login.setTabletTracking(False)
        self.login.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.login.setText("")
        self.login.setDragEnabled(False)
        self.login.setReadOnly(False)
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(auth_form)
        self.password.setGeometry(QtCore.QRect(60, 180, 361, 31))
        self.password.setTabletTracking(False)
        self.password.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.password.setText("")
        self.password.setDragEnabled(False)
        self.password.setObjectName("password")
        self.button_enter = QtWidgets.QPushButton(auth_form)
        self.button_enter.setGeometry(QtCore.QRect(60, 320, 361, 41))
        self.button_enter.setStyleSheet("QPushButton{ background-color:rgb(85, 85, 255); }\n"
"QAbstractButton{ color:rgb(255, 255, 255); font: 10pt \"MS Shell Dlg 2\"; }")
        self.button_enter.setAutoDefault(True)
        self.button_enter.setDefault(False)
        self.button_enter.setFlat(False)
        self.button_enter.setObjectName("button_enter")

        self.retranslateUi(auth_form)
        QtCore.QMetaObject.connectSlotsByName(auth_form)

    def retranslateUi(self, auth_form):
        _translate = QtCore.QCoreApplication.translate
        auth_form.setWindowTitle(_translate("auth_form", "Авторизация"))
        self.login.setWhatsThis(_translate("auth_form", "<html><head/><body><p><br/></p></body></html>"))
        self.login.setPlaceholderText(_translate("auth_form", "Логин"))
        self.password.setWhatsThis(_translate("auth_form", "<html><head/><body><p><br/></p></body></html>"))
        self.password.setPlaceholderText(_translate("auth_form", "Пароль"))
        self.button_enter.setText(_translate("auth_form", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    auth_form = QtWidgets.QDialog()
    ui = Ui_auth_form()
    ui.setupUi(auth_form)
    auth_form.show()
    sys.exit(app.exec_())
