# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_note_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_note_window(object):
    def setupUi(self, change_note_window):
        change_note_window.setObjectName("change_note_window")
        change_note_window.resize(471, 663)
        self.barcode = QtWidgets.QLineEdit(change_note_window)
        self.barcode.setGeometry(QtCore.QRect(50, 520, 361, 31))
        self.barcode.setTabletTracking(False)
        self.barcode.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.barcode.setDragEnabled(False)
        self.barcode.setReadOnly(False)
        self.barcode.setObjectName("barcode")
        self.button_save = QtWidgets.QPushButton(change_note_window)
        self.button_save.setGeometry(QtCore.QRect(50, 590, 361, 41))
        self.button_save.setStyleSheet("QPushButton{ background-color:rgb(85, 85, 255); }\n"
"QAbstractButton{ color:rgb(255, 255, 255); font: 10pt \"MS Shell Dlg 2\"; }")
        self.button_save.setAutoDefault(True)
        self.button_save.setDefault(False)
        self.button_save.setFlat(False)
        self.button_save.setObjectName("button_save")
        self.text_instruction = QtWidgets.QLabel(change_note_window)
        self.text_instruction.setGeometry(QtCore.QRect(50, 320, 91, 31))
        self.text_instruction.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_instruction.setObjectName("text_instruction")
        self.instruction_memo = QtWidgets.QLineEdit(change_note_window)
        self.instruction_memo.setGeometry(QtCore.QRect(50, 360, 361, 141))
        self.instruction_memo.setTabletTracking(False)
        self.instruction_memo.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.instruction_memo.setText("")
        self.instruction_memo.setDragEnabled(False)
        self.instruction_memo.setReadOnly(False)
        self.instruction_memo.setPlaceholderText("")
        self.instruction_memo.setObjectName("instruction_memo")
        self.text_name = QtWidgets.QLabel(change_note_window)
        self.text_name.setGeometry(QtCore.QRect(50, 90, 121, 31))
        self.text_name.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_name.setObjectName("text_name")
        self.choice_manufacturer = QtWidgets.QComboBox(change_note_window)
        self.choice_manufacturer.setGeometry(QtCore.QRect(50, 50, 361, 31))
        self.choice_manufacturer.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.choice_manufacturer.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.choice_manufacturer.setEditable(False)
        self.choice_manufacturer.setCurrentText("")
        self.choice_manufacturer.setDuplicatesEnabled(False)
        self.choice_manufacturer.setFrame(True)
        self.choice_manufacturer.setObjectName("choice_manufacturer")
        self.choice_pharmacology = QtWidgets.QComboBox(change_note_window)
        self.choice_pharmacology.setGeometry(QtCore.QRect(50, 260, 361, 31))
        self.choice_pharmacology.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.choice_pharmacology.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.choice_pharmacology.setEditable(False)
        self.choice_pharmacology.setCurrentText("")
        self.choice_pharmacology.setDuplicatesEnabled(False)
        self.choice_pharmacology.setFrame(True)
        self.choice_pharmacology.setObjectName("choice_pharmacology")
        self.choice_release = QtWidgets.QComboBox(change_note_window)
        self.choice_release.setGeometry(QtCore.QRect(50, 190, 361, 31))
        self.choice_release.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.choice_release.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.choice_release.setEditable(False)
        self.choice_release.setCurrentText("")
        self.choice_release.setDuplicatesEnabled(False)
        self.choice_release.setFrame(True)
        self.choice_release.setObjectName("choice_release")
        self.text_manufacturer = QtWidgets.QLabel(change_note_window)
        self.text_manufacturer.setGeometry(QtCore.QRect(50, 20, 121, 31))
        self.text_manufacturer.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_manufacturer.setObjectName("text_manufacturer")
        self.text_pharmacology = QtWidgets.QLabel(change_note_window)
        self.text_pharmacology.setGeometry(QtCore.QRect(50, 230, 221, 31))
        self.text_pharmacology.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_pharmacology.setObjectName("text_pharmacology")
        self.choice_name = QtWidgets.QComboBox(change_note_window)
        self.choice_name.setGeometry(QtCore.QRect(50, 120, 361, 31))
        self.choice_name.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.choice_name.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.choice_name.setEditable(False)
        self.choice_name.setCurrentText("")
        self.choice_name.setDuplicatesEnabled(False)
        self.choice_name.setFrame(True)
        self.choice_name.setObjectName("choice_name")
        self.text_release = QtWidgets.QLabel(change_note_window)
        self.text_release.setGeometry(QtCore.QRect(50, 160, 121, 31))
        self.text_release.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_release.setObjectName("text_release")

        self.retranslateUi(change_note_window)
        QtCore.QMetaObject.connectSlotsByName(change_note_window)

    def retranslateUi(self, change_note_window):
        _translate = QtCore.QCoreApplication.translate
        change_note_window.setWindowTitle(_translate("change_note_window", "Редактировать запись"))
        self.barcode.setWhatsThis(_translate("change_note_window", "<html><head/><body><p><br/></p></body></html>"))
        self.barcode.setText(_translate("change_note_window", "099890"))
        self.barcode.setPlaceholderText(_translate("change_note_window", "Штрих-код"))
        self.button_save.setText(_translate("change_note_window", "Сохранить"))
        self.text_instruction.setText(_translate("change_note_window", "Инструкция"))
        self.instruction_memo.setWhatsThis(_translate("change_note_window", "<html><head/><body><p><br/></p></body></html>"))
        self.text_name.setText(_translate("change_note_window", "Название"))
        self.text_manufacturer.setText(_translate("change_note_window", "Производитель"))
        self.text_pharmacology.setText(_translate("change_note_window", "Фармакологическая группа"))
        self.text_release.setText(_translate("change_note_window", "Форма выпуска"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    change_note_window = QtWidgets.QDialog()
    ui = Ui_change_note_window()
    ui.setupUi(change_note_window)
    change_note_window.show()
    sys.exit(app.exec_())
