# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_form(object):
    def setupUi(self, menu_form):
        menu_form.setObjectName("menu_form")
        menu_form.resize(474, 404)
        self.button_exit = QtWidgets.QPushButton(menu_form)
        self.button_exit.setGeometry(QtCore.QRect(60, 320, 361, 41))
        self.button_exit.setStyleSheet("QPushButton{ background-color:rgb(85, 85, 255); }\n"
"QAbstractButton{ color:rgb(255, 255, 255); font: 10pt \"MS Shell Dlg 2\"; }")
        self.button_exit.setAutoDefault(True)
        self.button_exit.setDefault(False)
        self.button_exit.setFlat(False)
        self.button_exit.setObjectName("button_exit")
        self.button_tables = QtWidgets.QPushButton(menu_form)
        self.button_tables.setGeometry(QtCore.QRect(60, 110, 361, 41))
        self.button_tables.setStyleSheet("QPushButton{ background-color: rgb(255, 255, 255); }\n"
"\n"
"QAbstractButton{ color:rgb(85, 85, 255); font: 75 11pt \"MS Shell Dlg 2\"; }\n"
"")
        self.button_tables.setAutoDefault(True)
        self.button_tables.setDefault(False)
        self.button_tables.setFlat(False)
        self.button_tables.setObjectName("button_tables")
        self.button_requests = QtWidgets.QPushButton(menu_form)
        self.button_requests.setGeometry(QtCore.QRect(60, 180, 361, 41))
        self.button_requests.setStyleSheet("QPushButton{ background-color: rgb(255, 255, 255); }\n"
"\n"
"\n"
"QAbstractButton{ color:rgb(85, 85, 255); font: 11pt \"MS Shell Dlg 2\"; }")
        self.button_requests.setAutoDefault(True)
        self.button_requests.setDefault(False)
        self.button_requests.setFlat(False)
        self.button_requests.setObjectName("button_requests")

        self.retranslateUi(menu_form)
        QtCore.QMetaObject.connectSlotsByName(menu_form)

    def retranslateUi(self, menu_form):
        _translate = QtCore.QCoreApplication.translate
        menu_form.setWindowTitle(_translate("menu_form", "Меню"))
        self.button_exit.setText(_translate("menu_form", "Выйти"))
        self.button_tables.setText(_translate("menu_form", "Таблицы"))
        self.button_requests.setText(_translate("menu_form", "Запросы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu_form = QtWidgets.QDialog()
    ui = Ui_menu_form()
    ui.setupUi(menu_form)
    menu_form.show()
    sys.exit(app.exec_())
