# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tables_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tables_window(object):
    def setupUi(self, tables_window):
        tables_window.setObjectName("tables_window")
        tables_window.resize(993, 649)
        self.button_menu = QtWidgets.QPushButton(tables_window)
        self.button_menu.setGeometry(QtCore.QRect(30, 40, 161, 41))
        self.button_menu.setStyleSheet("QPushButton{ background-color:rgb(85, 85, 255); }\n"
"QAbstractButton{ color:rgb(255, 255, 255); font: 10pt \"MS Shell Dlg 2\"; }")
        self.button_menu.setAutoDefault(True)
        self.button_menu.setDefault(False)
        self.button_menu.setFlat(False)
        self.button_menu.setObjectName("button_menu")
        self.button_change = QtWidgets.QPushButton(tables_window)
        self.button_change.setGeometry(QtCore.QRect(30, 210, 161, 41))
        self.button_change.setStyleSheet("QPushButton{ background-color: rgb(255, 255, 255); }\n"
"QAbstractButton{ color:rgb(85, 85, 255); font: 11pt \"MS Shell Dlg 2\"; }")
        self.button_change.setAutoDefault(True)
        self.button_change.setDefault(False)
        self.button_change.setFlat(False)
        self.button_change.setObjectName("button_change")
        self.button_add = QtWidgets.QPushButton(tables_window)
        self.button_add.setGeometry(QtCore.QRect(30, 160, 161, 41))
        self.button_add.setStyleSheet("QPushButton{ background-color: rgb(255, 255, 255); }\n"
"QAbstractButton{ color:rgb(85, 85, 255); font: 11pt \"MS Shell Dlg 2\"; }")
        self.button_add.setAutoDefault(True)
        self.button_add.setDefault(False)
        self.button_add.setFlat(False)
        self.button_add.setObjectName("button_add")
        self.button_generate = QtWidgets.QPushButton(tables_window)
        self.button_generate.setGeometry(QtCore.QRect(30, 260, 161, 41))
        self.button_generate.setStyleSheet("QPushButton{ background-color: rgb(255, 255, 255); }\n"
"QAbstractButton{ color:rgb(85, 85, 255); font: 11pt \"MS Shell Dlg 2\"; }")
        self.button_generate.setAutoDefault(True)
        self.button_generate.setDefault(False)
        self.button_generate.setFlat(False)
        self.button_generate.setObjectName("button_generate")
        self.text_work_notes = QtWidgets.QLabel(tables_window)
        self.text_work_notes.setGeometry(QtCore.QRect(30, 129, 151, 21))
        self.text_work_notes.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_work_notes.setObjectName("text_work_notes")
        self.button_all = QtWidgets.QPushButton(tables_window)
        self.button_all.setGeometry(QtCore.QRect(30, 370, 161, 41))
        self.button_all.setStyleSheet("QPushButton{ background-color: rgb(255, 255, 255); }\n"
"QAbstractButton{ color:rgb(85, 85, 255); font: 11pt \"MS Shell Dlg 2\"; }")
        self.button_all.setAutoDefault(True)
        self.button_all.setDefault(False)
        self.button_all.setFlat(False)
        self.button_all.setObjectName("button_all")
        self.button_open = QtWidgets.QPushButton(tables_window)
        self.button_open.setGeometry(QtCore.QRect(30, 420, 161, 41))
        self.button_open.setStyleSheet("QPushButton{ background-color: rgb(255, 255, 255); }\n"
"QAbstractButton{ color:rgb(85, 85, 255); font: 11pt \"MS Shell Dlg 2\"; }")
        self.button_open.setAutoDefault(True)
        self.button_open.setDefault(False)
        self.button_open.setFlat(False)
        self.button_open.setObjectName("button_open")
        self.text_work_tables = QtWidgets.QLabel(tables_window)
        self.text_work_tables.setGeometry(QtCore.QRect(30, 340, 161, 21))
        self.text_work_tables.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_work_tables.setObjectName("text_work_tables")
        self.button_delete = QtWidgets.QPushButton(tables_window)
        self.button_delete.setGeometry(QtCore.QRect(30, 470, 161, 41))
        self.button_delete.setStyleSheet("QPushButton{ background-color: rgb(255, 255, 255); }\n"
"QAbstractButton{ color:rgb(85, 85, 255); font: 11pt \"MS Shell Dlg 2\"; }")
        self.button_delete.setAutoDefault(True)
        self.button_delete.setDefault(False)
        self.button_delete.setFlat(False)
        self.button_delete.setObjectName("button_delete")
        self.text_column = QtWidgets.QLabel(tables_window)
        self.text_column.setGeometry(QtCore.QRect(240, 570, 71, 31))
        self.text_column.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_column.setObjectName("text_column")
        self.button_search = QtWidgets.QPushButton(tables_window)
        self.button_search.setGeometry(QtCore.QRect(800, 530, 161, 41))
        self.button_search.setStyleSheet("QPushButton{ background-color:rgb(85, 85, 255); }\n"
"QAbstractButton{ color:rgb(255, 255, 255); font: 10pt \"MS Shell Dlg 2\"; }")
        self.button_search.setAutoDefault(True)
        self.button_search.setDefault(False)
        self.button_search.setFlat(False)
        self.button_search.setObjectName("button_search")
        self.choice_table = QtWidgets.QComboBox(tables_window)
        self.choice_table.setGeometry(QtCore.QRect(320, 530, 161, 31))
        self.choice_table.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.choice_table.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.choice_table.setEditable(False)
        self.choice_table.setCurrentText("")
        self.choice_table.setDuplicatesEnabled(False)
        self.choice_table.setFrame(True)
        self.choice_table.setObjectName("choice_table")
        self.text_table = QtWidgets.QLabel(tables_window)
        self.text_table.setGeometry(QtCore.QRect(240, 530, 71, 31))
        self.text_table.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_table.setObjectName("text_table")
        self.choice_column = QtWidgets.QComboBox(tables_window)
        self.choice_column.setGeometry(QtCore.QRect(320, 570, 161, 31))
        self.choice_column.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.choice_column.setStyleSheet("QLineEdit{ font: 10pt \"MS Shell Dlg 2\"; }")
        self.choice_column.setEditable(False)
        self.choice_column.setCurrentText("")
        self.choice_column.setDuplicatesEnabled(False)
        self.choice_column.setFrame(True)
        self.choice_column.setObjectName("choice_column")
        self.tableWidget_tables = QtWidgets.QTableWidget(tables_window)
        self.tableWidget_tables.setGeometry(QtCore.QRect(240, 30, 721, 481))
        self.tableWidget_tables.setObjectName("tableWidget")
        self.tableWidget_tables.setColumnCount(0)
        self.tableWidget_tables.setRowCount(0)
        self.search_medicine = QtWidgets.QTextEdit(tables_window)
        self.search_medicine.setGeometry(QtCore.QRect(620, 530, 161, 31))
        self.search_medicine.setObjectName("search_medicine")
        self.search_pharmacy = QtWidgets.QTextEdit(tables_window)
        self.search_pharmacy.setGeometry(QtCore.QRect(620, 570, 161, 31))
        self.search_pharmacy.setObjectName("search_pharmacy")
        self.text_medicine = QtWidgets.QLabel(tables_window)
        self.text_medicine.setGeometry(QtCore.QRect(520, 530, 81, 31))
        self.text_medicine.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_medicine.setObjectName("text_medicine")
        self.text_pharmacy = QtWidgets.QLabel(tables_window)
        self.text_pharmacy.setGeometry(QtCore.QRect(550, 570, 61, 31))
        self.text_pharmacy.setStyleSheet("QLabel{ color:rgb(111, 111, 111); font: 10pt \"MS Shell Dlg 2\"; }\n"
"")
        self.text_pharmacy.setObjectName("text_pharmacy")

        self.retranslateUi(tables_window)
        QtCore.QMetaObject.connectSlotsByName(tables_window)

    def retranslateUi(self, tables_window):
        _translate = QtCore.QCoreApplication.translate
        tables_window.setWindowTitle(_translate("tables_window", "Таблицы"))
        self.button_menu.setText(_translate("tables_window", "Меню"))
        self.button_change.setText(_translate("tables_window", "Редактировать"))
        self.button_add.setText(_translate("tables_window", "Добавить"))
        self.button_generate.setText(_translate("tables_window", "Генерация"))
        self.text_work_notes.setText(_translate("tables_window", "Работа с записями"))
        self.button_all.setText(_translate("tables_window", "Все записи"))
        self.button_open.setText(_translate("tables_window", "Открыть"))
        self.text_work_tables.setText(_translate("tables_window", "Работа с таблицами"))
        self.button_delete.setText(_translate("tables_window", "Удалить"))
        self.text_column.setText(_translate("tables_window", "Столбец"))
        self.button_search.setText(_translate("tables_window", "Поиск"))
        self.text_table.setText(_translate("tables_window", "Таблица"))
        self.text_medicine.setText(_translate("tables_window", "Лекарство"))
        self.text_pharmacy.setText(_translate("tables_window", "Аптека"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tables_window = QtWidgets.QDialog()
    ui = Ui_tables_window()
    ui.setupUi(tables_window)
    tables_window.show()
    sys.exit(app.exec_())
